# excluded: BIOSQLSP/SG_COMMENT.csv

./gradlew :spider:assemble
java \
-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 \
-Xmx4g \
-cp metanome-cli-1.1.1-SNAPSHOT.jar:spider/build/libs/spider-0.1.0-SNAPSHOT-file.jar  \
de.metanome.cli.App \
--algorithm de.metanome.algorithms.spider.SpiderFileAlgorithm \
--file-key TABLE \
--files \
BIOSQLSP/SG_BIODATABASE.csv \
BIOSQLSP/SG_BIOSEQUENCE.csv \
BIOSQLSP/SG_SEQFEATURE.csv \
BIOSQLSP/SG_TERM.csv \
BIOSQLSP/SG_BIODATABASE_QUALIFIER_ASSOC.csv \
BIOSQLSP/SG_SEQFEATURE_ASSOC.csv \
BIOSQLSP/SG_TERM_ASSOC.csv \
BIOSQLSP/SG_BIOENTRY.csv \
BIOSQLSP/SG_DBXREF.csv \
BIOSQLSP/SG_SEQFEATURE_DBXREF_ASSOC.csv \
BIOSQLSP/SG_TERM_DBXREF_ASSOC.csv \
BIOSQLSP/SG_BIOENTRY_ASSOC.csv \
BIOSQLSP/SG_DBXREF_QUALIFIER_ASSOC.csv \
BIOSQLSP/SG_SEQFEATURE_PATH.csv \
BIOSQLSP/SG_TERM_PATH.csv \
BIOSQLSP/SG_BIOENTRY_DBXREF_ASSOC.csv \
BIOSQLSP/SG_LOCATION.csv \
BIOSQLSP/SG_SEQFEATURE_QUALIFIER_ASSOC.csv \
BIOSQLSP/SG_TERM_SYNONYM.csv \
BIOSQLSP/SG_BIOENTRY_PATH.csv \
BIOSQLSP/SG_LOCATION_QUALIFIER_ASSOC.csv \
BIOSQLSP/SG_SIMILARITY.csv \
BIOSQLSP/SG_BIOENTRY_QUALIFIER_ASSOC.csv \
BIOSQLSP/SG_ONTOLOGY.csv \
BIOSQLSP/SG_TAXON.csv \
BIOSQLSP/SG_BIOENTRY_REF_ASSOC.csv \
BIOSQLSP/SG_REFERENCE.csv \
BIOSQLSP/SG_TAXON_NAME.csv \
--escape \\ \
--algorithm-config   INPUT_ROW_LIMIT:-1,MAX_MEMORY_USAGE:2097152,MEMORY_CHECK_INTERVAL:10000 \
--output file \
--temp /some/temp/directory
